---
- name: Installation des prérequis sur le serveur distant
  hosts: servers
  become: true
  become_method: sudo
  remote_user: provision
  tasks:
    - name: Désactiver les dépôts tiers non officiels
      shell: |
        echo "Désactivation temporaire des dépôts non officiels..."
        find /etc/apt/sources.list.d -type f -name '*.list' -exec sed -i 's/^deb/#deb/' {} \;
      ignore_errors: yes

    - name: Mettre à jour le cache APT
      apt:
        update_cache: yes
      ignore_errors: yes

    - name: Installer les dépendances de base
      apt:
        name:
          - git
          - curl
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present
        update_cache: yes
      ignore_errors: yes
    - name: Ajouter la clé GPG officielle de Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Ajouter le dépôt officiel Docker
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present
    - name: Installer Docker et Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
        update_cache: yes
    - name: Ajouter l’utilisateur courant au groupe docker
      user:
        name: '{{ ansible_user }}'
        groups: docker
        append: yes
    - name: Activer et démarrer le service Docker
      systemd:
        name: docker
        enabled: yes
        state: started
    - name: Vérifier la version de Docker
      command: docker --version
      register: docker_version_output
      changed_when: false
    - name: Vérifier la version de Docker Compose
      command: docker compose version
      register: compose_version_output
      changed_when: false
    - name: Afficher les résultats
      debug:
        msg:
          - 'Docker installé avec succès : {{ docker_version_output.stdout }}'
          - 'Docker Compose installé : {{ compose_version_output.stdout }}'